name: Sync kong from upstream

on:
  # schedule:
  #   - cron: '*/5 7-20 * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-kong-app-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Sync kong from upstream
        uses: giantswarm/subtree-util@v0.1.2
        with:
          target_github_token: ${{ secrets.ARCHITECT_BOT_GITHUB_REPO_SYNC_TOKEN }}
          target_repository: giantswarm/kong-app
          target_path: helm/kong-app
          source_tag_wildcard: "kong-*"
          source_path: charts/kong
